name: Hello Universe
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: gtamang001/javascript-actions@main
        with:
          who-to-greet: 'Ganga Tamang'
