name: Test Action to check javascript action
on:
  push: 
    branches: 
      - develop

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Check input and output for javascript action
    steps:
      - name: Hello world action step
        id: hello
        uses: gtamang001/javascript-actions@develop
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: |
          echo "The time was ${{ steps.hello.outputs.time }}"
          echo "The name was ${{ steps.hello.outputs.name}}"
    # added comment 